name: 'Composite Action Example'
description: 'A composite action to checkout code and set up Node.js'
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
   
      
    - name: Set up python
      uses: aparnajyothi-y/setup-python@enhance-cache-dependency-path
      with:
        python-version : '3.12'
        cache: 'pipenv'
        cache-dependency-path: Pipfile.lock
    - name: Install pipenv
      run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
      shell: bash
    - run: pipenv install
      shell: bash
        
        
        

