name: Container Diagnosis

on: 
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    container: ghcr.io/iterative/cml:0-dvc3-base1
    strategy:
      fail-fast: false
      matrix:
        version: [3.8, 3.9]  
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
      - run: |
          mkdir -p /github/home/.cache/pip
          sudo chown -R $(whoami) /github/home/.cache/pip

      
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version }}
          cache: 'pip' # caching pip dependencies
      # Install requirements
      - run: pip install -r requirements.txt
