name: 1157 error

on: 
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/iterative/cml:0-dvc3-base1
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
      - name: Clear Python cache
        run: |
          sudo rm -rf /__t/Python
      - name: Change ownership of /github/home
        run: sudo chown $(whoami) ~/.cache ~/.config
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      - name: Install requirements
        run: |
          pip install -r requirements.txt
