name: Python Location Test

on: 
  workflow_dispatch:

jobs:
  test-with-container:
    runs-on: ubuntu-latest
    container: ghcr.io/iterative/cml:0-dvc3-base1
    steps:
      - name: Before setup-python
        run: |
          echo "=== BEFORE SETUP-PYTHON ==="
          whoami
          which python3 2>/dev/null || echo "python3 not found"
          which pip3 2>/dev/null || echo "pip3 not found"
        
      - name: Change ownership
        run: sudo chown -R $(whoami) /github/home
        
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          
      - name: After setup-python
        run: |
          echo "=== AFTER SETUP-PYTHON ==="
          which python3
          which pip3
          python3 --version
          pip3 --version
          
          echo -e "\n=== Path Comparison ==="
          echo "Current python3: $(which python3)"
          echo "Expected setup-python path: /__t/Python/3.13.*/x64/bin/python3"
          ls -la /__t/Python/*/x64/bin/ 2>/dev/null || echo "Setup-python path not found"

  test-without-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Check installation location
        run: |
          echo "=== WITHOUT CONTAINER ==="
          which python3
          which pip3
          python3 -c "import sys; print('Python path:', sys.executable)"
          ls -la /opt/hostedtoolcache/Python/ 2>/dev/null || echo "Hostedtoolcache not found"
