name: Container Diagnosis

on: 
  workflow_dispatch:

jobs:
  diagnose:
    runs-on: ubuntu-latest
    container: ghcr.io/iterative/cml:0-dvc3-base1
    steps:
      - name: Full system diagnosis
        run: |
          echo "=== Container OS Information ==="
          cat /etc/os-release
          uname -a
          
          echo -e "\n=== GLIBC Version in Container ==="
          ldd --version
          strings /lib/x86_64-linux-gnu/libc.so.6 | grep GLIBC_ | sort -V | tail -10
          
          echo -e "\n=== Container's Built-in Python ==="
          /usr/bin/python3 --version 2>/dev/null || echo "No python3 in /usr/bin"
          /usr/local/bin/python3 --version 2>/dev/null || echo "No python3 in /usr/local/bin"
          which python3
          python3 --version
          
          echo -e "\n=== GitHub Runner Host OS (for comparison) ==="
          # This will show what setup-python binaries are compiled for
