name: 1167 error

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13.6

      - name: Install poetry
        run: |
          pipx install poetry
          poetry --version

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13.6
          cache: 'poetry'
          
      - name: Set Poetry Python version
        run: |
            poetry env use 3.13.6
            poetry env info

      - name: Install dependencies
        run: poetry install
      
     
