name: 1167 error

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # - name: Install Poetry with pipx
      #   run: pipx install poetry
      
      - name: Use Python 3.13.3
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.3"
          cache: "poetry"
      
      - name: Install Poetry
        run: pip install poetry
    
      - name: Set Poetry Environment
        run: poetry env use 3.13
