name: 1167 error

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "poetry"

      - name: Install pipx
        run: python -m pip install --user pipx && python -m pipx ensurepath
      - name: Install poetry
        run: pipx install poetry
      - name: Install dependencies
        run: poetry install
      - name: Check Python and Poetry version
        run: |
          python --version
          poetry --version
