name: 1167 error

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubnuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "poetry"

      - name: Install poetry
        run: pipx install poetry
