name: 1167 error

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
 
      - name: Install poetry
        run: |
          pipx install poetry
          poetry --version
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13.3
          cache: 'poetry'

      # - name: Install dependencies
      #   run: poetry install

      # - name: "Install OS dependencies"
      #   run: |
      #     sudo apt update
      #     sudo apt install --no-install-recommends --no-install-suggests -y \
      #       build-essential python3.13-dev python3-psutil \
      #       libffi8 libldap-dev libldap2 libsasl2-dev libssl-dev libgeos-c1v5

      - name: "Run poetry install"
        env:
          POETRY_CACHE_DIR: ~/.cache/pypoetry
        run: poetry install --with test
      
     
